networks:
  cv-network:
    driver: bridge

services:
  mysql-db:
    container_name: carvalue-db
    image: mysql:8.0  
    restart: always
    ports:
      - "3306:3306"  
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} 
      MYSQL_DATABASE: ${MYSQL_DATABASE}  
      MYSQL_USER: ${MYSQL_USER}      
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql 
      - ./data/db-init:/docker-entrypoint-initdb.d/  
    networks:
      - cv-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin  
    container_name: cv-phpmyadmin
    restart: always
    depends_on:
      - mysql-db
    ports:
      - "8080:80"  
    environment:
      PMA_HOST: ${PMA_HOST}
      PMA_USER: ${PMA_USER}      
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}  
    networks:
      - cv-network

  cv-api:
    container_name: cv-api
    build: .  
    ports:
      - "3000:3000"  
    command: npm run start:dev  
    restart: always
    volumes:
      - .:/usr/src/app  
      - /usr/src/app/node_modules  
    environment:
      DATABASE_URL: ${DATABASE_URL}  
    depends_on:
      - mysql-db  
    networks:
      - cv-network

volumes:
  mysql-data:  